### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Afantor** [kmolLin/Pyquino#2]
hello,when I run "python3 launchPyquino.py" by PyCharm IDE,I get some SyntaxError:
Traceback (most recent call last):
  File "D:/Micro_Tool/Pyquino/launchPyquino.py", line 6, in <module>
    from core.mainwindow import MainWindow
  File "D:\Micro_Tool\Pyquino\core\mainwindow.py", line 10, in <module>
    from .RightClick import rightClick
  File "D:\Micro_Tool\Pyquino\core\RightClick.py", line 22
    action = QAction(f"print{i}", self)
                               ^
SyntaxError: invalid syntax

how I can fix it?

**Comment by kmolLin** [comment]
Sorry late for reply you Question.
There where be a big change in this repository. Give me some time to solve this Question 
: D
